text_encoders:
  - repo: "comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI"
    repo_path: "text_encoders/oldt5_xxl_fp8_e4m3fn_scaled.safetensors"
    local_dir: "cosmos"
    local_name: "oldt5_xxl_fp8_e4m3fn_scaled.safetensors"
    model_categories: ["cosmos"]
  - repo: "Comfy-Org/Wan_2.1_ComfyUI_repackaged"
    repo_path: "split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors"
    local_dir: "WAN"
    local_name: "umt5_xxl_fp8_e4m3fn_scaled.safetensors"
    model_categories: ["wan"]
  - repo: "Comfy-Org/mochi_preview_repackaged"
    repo_path: "split_files/text_encoders/t5xxl_fp16.safetensors"
    local_dir: "ltxv"
    local_name: "t5xxl_fp16.safetensors"
    model_categories: ["ltxv"]

clip:
  - repo: "comfyanonymous/flux_text_encoders"
    repo_path: "clip_l.safetensors"
    local_dir: ""
    local_name: "clip_l.safetensors"
    model_categories: ["all"]
  - repo: "comfyanonymous/flux_text_encoders"
    repo_path: "t5xxl_fp16.safetensors"
    local_dir: "FLUX"
    local_name: "t5xxl_fp16.safetensors"
    model_categories: ["flux_high"]
  - repo: "city96/t5-v1_1-xxl-encoder-gguf"
    repo_path: "t5-v1_1-xxl-encoder-Q8_0.gguf"
    local_dir: "FLUX"
    local_name: "t5-v1_1-xxl-encoder-Q8_0.gguf"
    model_categories: ["flux_low"]
  - repo: "comfyanonymous/flux_text_encoders"
    repo_path: "t5xxl_fp8_e4m3fn.safetensors"
    local_dir: "FLUX"
    local_name: "t5xxl_fp8_e4m3fn.safetensors"
    model_categories: ["flux_low"]
  - repo: "Comfy-Org/HunyuanVideo_repackaged"
    repo_path: "split_files/text_encoders/clip_l.safetensors"
    local_dir: "HUNYUAN"
    local_name: "clip_l.safetensors"
    model_categories: ["hunyuan"]
  - repo: "stabilityai/stable-diffusion-3.5-large"
    repo_path: "text_encoders/clip_g.safetensors"
    local_dir: "SD35"
    local_name: "clip_g.safetensors"
    model_categories: ["sd35"]
  - repo: "stabilityai/stable-diffusion-3.5-large"
    repo_path: "text_encoders/t5xxl_fp8_e4m3fn.safetensors"
    local_dir: "SD35"
    local_name: "t5xxl_fp8_e4m3fn.safetensors"
    model_categories: ["sd35"]

clip_vision:
  - repo: "Comfy-Org/Wan_2.1_ComfyUI_repackaged"
    repo_path: "split_files/clip_vision/clip_vision_h.safetensors"
    local_dir: "WAN"
    local_name: "clip_vision_h.safetensors"
    model_categories: ["wan"]

checkpoints:
  - repo: "stabilityai/stable-diffusion-xl-base-1.0"
    repo_path: "sd_xl_base_1.0.safetensors"
    local_dir: "SDXL"
    local_name: "sd_xl_base_1.0.safetensors"
    model_categories: ["sdxl"]
  - repo: "stable-diffusion-3.5-large"
    repo_path: "sd3.5_large.safetensors"
    local_dir: "SD35"
    local_name: "sd3.5_large.safetensors"
    model_categories: ["sd35"]
  - repo: "Lightricks/LTX-Video"
    repo_path: "ltx-video-2b-v0.9.5.safetensors"
    local_dir: "ltxv"
    local_name: "ltx-video-2b-v0.9.5.safetensors"
    model_categories: ["ltxv"]

unet:
  - repo: "city96/HunyuanVideo-gguf"
    repo_path: "hunyuan-video-t2v-720p-Q8_0.gguf"
    local_dir: "HUNYUAN"
    local_name: "hunyuan-video-t2v-720p-Q8_0.gguf"
    model_categories: ["hunyuan_low"]
  - repo: "city96/FLUX.1-dev-gguf"
    repo_path: "flux1-dev-Q8_0.gguf"
    local_dir: "FLUX"
    local_name: "flux1-dev-Q8_0.gguf"
    model_categories: ["flux_low"]

diffusion_models:
  - repo: "cocktailpeanut/xulf-dev"
    repo_path: "flux1-dev.safetensors"
    local_dir: "FLUX"
    local_name: "flux1-dev.safetensors"
    model_categories: ["flux_high"]
  - repo: "Comfy-Org/HunyuanVideo_repackaged"
    repo_path: "split_files/diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors"
    local_dir: "HUNYUAN"
    local_name: "hunyuan_video_t2v_720p_bf16.safetensors"
    model_categories: ["hunyuan_high"]
  - repo: "mcmonkey/cosmos-1.0"
    repo_path: "Cosmos-1_0-Diffusion-7B-Video2World.safetensors"
    local_dir: "cosmos"
    local_name: "Cosmos-1_0-Diffusion-7B-Video2World.safetensors"
    model_categories: ["cosmos_video"]
  - repo: "mcmonkey/cosmos-1.0"
    repo_path: "Cosmos-1_0-Diffusion-7B-Text2World.safetensors"
    local_dir: "cosmos"
    local_name: "Cosmos-1_0-Diffusion-7B-Text2World.safetensors"
    model_categories: ["cosmos_text"]
  - repo: "Comfy-Org/Wan_2.1_ComfyUI_repackaged"
    repo_path: "split_files/diffusion_models/wan2.1_i2v_480p_14B_bf16.safetensors"
    local_dir: "WAN"
    local_name: "wan2.1_i2v_480p_14B_bf16.safetensors"
    model_categories: ["wan-i2v"]
  - repo: "Comfy-Org/Wan_2.1_ComfyUI_repackaged"
    repo_path: "split_files/diffusion_models/wan2.1_t2v_14B_fp16.safetensors"
    local_dir: "WAN"
    local_name: "wan2.1_t2v_14B_fp16.safetensors"
    model_categories: ["wan-t2v"]


upscale_models:
  - repo: "Phips/4xNomos8kDAT"
    repo_path: "4xNomos8kDAT.safetensors"
    local_dir: ""
    local_name: "4xNomos8kDAT.safetensors"
    model_categories: ["all"]

vae:
  - repo: "cocktailpeanut/xulf-dev"
    repo_path: "ae.safetensors"
    local_dir: "FLUX"
    local_name: "ae.safetensors"
    model_categories: ["all"]
  - repo: "Comfy-Org/HunyuanVideo_repackaged"
    repo_path: "split_files/vae/hunyuan_video_vae_bf16.safetensors"
    local_dir: "HUNYUAN"
    local_name: "hunyuan_video_vae_bf16.safetensors"
    model_categories: ["all"]
  - repo: "comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI"
    repo_path: "vae/cosmos_cv8x8x8_1.0.safetensors"
    local_dir: "cosmos"
    local_name: "cosmos_cv8x8x8_1.0.safetensors"
    model_categories: ["cosmos"]
  - repo: "Comfy-Org/Wan_2.1_ComfyUI_repackaged"
    repo_path: "split_files/vae/wan_2.1_vae.safetensors"
    local_dir: "WAN"
    local_name: "wan_2.1_vae.safetensors"
    model_categories: ["wan"]
  - repo: "Lightricks/LTX-Video"
    repo_path: "diffusion_pytorch_model.safetensors"
    local_dir: "ltxv"
    local_name: "ltxv_vae.safetensors"
    model_categories: ["ltxv"]

loras:
  - repo: "comfyanonymous/flux_RealismLora_converted_comfyui"
    repo_path: "flux_realism_lora.safetensors"
    local_dir: "FLUX"
    local_name: "flux_realism_lora.safetensors"
    model_categories: ["flux_lora"]
  - repo: "iradraz/loras"
    repo_path: "1r4d-000012.safetensors"
    local_dir: "FLUX"
    local_name: "1r4d-000012.safetensors"
    model_categories: ["flux_lora"]
  - repo: "latent-consistency/lcm-lora-sdxl"
    repo_path: "pytorch_lora_weights.safetensors"
    local_dir: "SDXL"
    local_name: "LCM_LoRA_Weights_SDXL.safetensors"
    model_categories: ["sdxl_lora"]

controlnet:
  - repo: "jasperai/Flux.1-dev-Controlnet-Upscaler"
    repo_path: "diffusion_pytorch_model.safetensors"
    local_dir: "FLUX"
    local_name: "Flux.1-dev-Controlnet-Upscaler.safetensors"
    model_categories: ["flux_controlnet"]
  - repo: "jasperai/Flux.1-dev-Controlnet-Upscaler"
    repo_path: "diffusion_pytorch_model.safetensors"
    local_dir: "SD15"
    local_name: "control_v11p_sd15_canny_fp16.safetensors"
    model_categories: ["sd15_controlnet"]
  - repo: "InstantX/FLUX.1-dev-Controlnet-Union"
    repo_path: "diffusion_pytorch_model.safetensors"
    local_dir: "FLUX"
    local_name: "FLUX.1-dev-Controlnet-Union.safetensors"
    model_categories: ["flux_controlnet"]
  - repo: "InstantX/FLUX.1-dev-Controlnet-Canny"
    repo_path: "diffusion_pytorch_model.safetensors"
    local_dir: "FLUX"
    local_name: "FLUX.1-dev-Controlnet-Canny.safetensors"
    model_categories: ["flux_controlnet"]
  - repo: "stabilityai/stable-diffusion-3.5-controlnets"
    repo_path: "sd3.5_large_controlnet_canny.safetensors"
    local_dir: "SD35"
    local_name: "sd3.5_large_controlnet_canny.safetensors"
    model_categories: ["sd35_controlnet"]


pulid:
  - repo: "guozinan/PuLID"
    repo_path: "pulid_flux_v0.9.1.safetensors"
    local_dir: "pulid"
    local_name: "pulid_flux_v0.9.1.safetensors"
    model_categories: ["flux_pulid"]
# mmaudio:
#   - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors"
#     name: "apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors"
#     model_categories: ["mmaudio"]
#   - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/mmaudio_large_44k_v2_fp16.safetensors"
#     name: "mmaudio_large_44k_v2_fp16.safetensors"
#     model_categories: ["mmaudio"]
#   - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/mmaudio_synchformer_fp16.safetensors"
#     name: "mmaudio_synchformer_fp16.safetensors"
#     model_categories: ["mmaudio"]
#   - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/mmaudio_vae_44k_fp16.safetensors"
#     name: "mmaudio_vae_44k_fp16.safetensors"
#     model_categories: ["mmaudio"]