clip:
  - url: "https://huggingface.com/comfyanonymous/flux_text_encoders/resolve/main/clip_l.safetensors"
    name: "clip_l.safetensors"
    model_categories: ["all"]
  - url: "https://huggingface.com/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp16.safetensors"
    name: "FLUX/t5xxl_fp16.safetensors"
    model_categories: ["flux_high"]
  - url: "https://huggingface.com/city96/t5-v1_1-xxl-encoder-gguf/resolve/main/t5-v1_1-xxl-encoder-Q8_0.gguf"
    name: "FLUX/t5-v1_1-xxl-encoder-Q8_0.gguf"
    model_categories: ["flux_low"]
  - url: "https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp8_e4m3fn.safetensors"
    name: "FLUX/t5xxl_fp8_e4m3fn.safetensors"
    model_categories: ["flux_low"]
  - url: "https://huggingface.com/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/text_encoders/llava_llama3_fp8_scaled.safetensors"
    name: "HUNYUAN/llava_llama3_fp8_scaled.safetensors"
    model_categories: ["hunyuan"]

checkpoints:
  - url: "https://huggingface.com/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors"
    name: "SDXL/sd_xl_base_1.0.sensors"
    model_categories: ["sdxl"]
  - url: "https://civitai.com/api/download/models/119057?type=Model&format=SafeTensor&size=pruned&fp=fp16"
    name: "SD15/meinamix_meinaV11.safetensors"
    model_categories: ["sd15"]

unet:
   - url: "https://huggingface.com/city96/HunyuanVideo-gguf/resolve/main/hunyuan-video-t2v-720p-Q8_0.gguf"
     name: "HUNYUAN/hunyuan-video-t2v-720p-Q8_0.gguf"
     model_categories: ["hunyuan_low"]   
   - url: "https://huggingface.com/city96/FLUX.1-dev-gguf/resolve/main/flux1-dev-Q8_0.gguf"
     name: "FLUX/flux1-dev-Q8_0.gguf"
     model_categories: ["flux_low"]


diffusion_models:
  - url: "https://huggingface.com/cocktailpeanut/xulf-dev/resolve/main/flux1-dev.safetensors"
    name: "FLUX/flux1-dev.safetensors"
    model_categories: ["flux_high"]
  - url: "https://huggingface.com/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors"
    name: "HUNYUAN/hunyuan_video_t2v_720p_bf16.safetensors"
    model_categories: ["hunyuan_high"]

upscale_models:
  - url: "https://huggingface.com/Phips/4xNomos8kDAT/resolve/main/4xNomos8kDAT.safetensors"
    name: "4xNomos8kDAT.safetensors"
    model_categories: ["all"]

vae:
  - url: "https://huggingface.com/cocktailpeanut/xulf-dev/resolve/main/ae.safetensors"
    name: "FLUX/ae.safetensors"
    model_categories: ["all"]
  - url: "https://civitai.com/api/download/models/948574?type=VAE&format=SafeTensor"
    name: "SD15/kl-f8-anime2.safetensors"
    model_categories: ["all"]
  - url: "https://huggingface.com/Comfy-Org/HunyuanVideo_repackaged/resolve/main/split_files/vae/hunyuan_video_vae_bf16.safetensors"
    name: "HUNYUAN/hunyuan_video_vae_bf16.safetensors"
    model_categories: ["all"]

loras:
  - url: "https://civitai.com/api/download/models/805898?type=Model&format=SafeTensor"
    name: "FLUX/Aesthetic_Amateur_Photo_V3.safetensors"
    model_categories: ["flux_lora"]
  - url: "https://huggingface.com/comfyanonymous/flux_RealismLora_converted_comfyui/resolve/main/flux_realism_lora.safetensors"
    name: "FLUX/flux_realism_lora.safetensors"
    model_categories: ["flux_lora"]
  - url: "https://huggingface.com/latent-consistency/lcm-lora-sdxl/resolve/main/pytorch_lora_weights.safetensors"
    name: "SDXL/LCM_LoRA_Weights_SDXL.safetensors"
    model_categories: ["sdxl_lora"]

controlnet:
  - url: "https://huggingface.com/jasperai/Flux.1-dev-Controlnet-Upscaler/resolve/main/diffusion_pytorch_model.safetensors"
    name: "FLUX/Flux.1-dev-Controlnet-Upscaler.safetensors"
    model_categories: ["flux_controlnet"]
  - url: "https://huggingface.com/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_v11p_sd15_canny_fp16.safetensors"
    name: "SD15/control_v11p_sd15_canny_fp16.safetensors"
    model_categories: ["sd15_controlnet"]
  - url: "https://huggingface.com/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_v11p_sd15_openpose_fp16.safetensors"
    name: "SD15/control_v11p_sd15_openpose_fp16.safetensors"
    model_categories: ["sd15_controlnet"]
  - url: "https://huggingface.com/InstantX/FLUX.1-dev-Controlnet-Union/resolve/main/diffusion_pytorch_model.safetensors"
    name: "FLUX/FLUX.1-dev-Controlnet-Union.safetensors"
    model_categories: ["flux_controlnet"]
  - url: "https://huggingface.com/InstantX/FLUX.1-dev-Controlnet-Canny/resolve/main/diffusion_pytorch_model.safetensors"
    name: "FLUX/FLUX.1-dev-Controlnet-Canny.safetensors"
    model_categories: ["flux_controlnet"]

mmaudio:
  - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors"
    name: "apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors"
    model_categories: ["mmaudio"]
  - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/mmaudio_large_44k_v2_fp16.safetensors"
    name: "mmaudio_large_44k_v2_fp16.safetensors"
    model_categories: ["mmaudio"]
  - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/mmaudio_synchformer_fp16.safetensors"
    name: "mmaudio_synchformer_fp16.safetensors"
    model_categories: ["mmaudio"]
  - url: "https://huggingface.com/Kijai/MMAudio_safetensors/resolve/main/mmaudio_vae_44k_fp16.safetensors"
    name: "mmaudio_vae_44k_fp16.safetensors"
    model_categories: ["mmaudio"]